### ISSUE TITLE
System.Collections.Generic.KeyNotFoundException after version update

### ISSUE THREAD

**Issue by ondrasvoboda** [XAMLMarkupExtensions/XAMLMarkupExtensions#114]
I updated the WPFLocalizationExtension nuget package from 3.8.0 to 3.9.0.
In this case XAMLMarkupExtensions automatically were updated from 2.0.0 to 2.1.1.

After that I'm quite often getting the following exception. But still I don't know what is causing it, it just shows 'sometimes'. Maybe somebody else is having some similar troubles. Thank you for any help.

```
System.Windows.Markup.XamlParseException: The given key was not present in the dictionary. ---> System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.ThrowHelper.ThrowKeyNotFoundException()
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at XAMLMarkupExtensions.Base.TargetObjectsList.AddTargetObjectProperty(WeakReference targetObjectWeakReference, Object targetProperty, Type targetPropertyType, Int32 targetPropertyIndex) in D:\a\XAMLMarkupExtensions\XAMLMarkupExtensions\src\Base\TargetObjectsList.cs:line 82
   at XAMLMarkupExtensions.Base.NestedMarkupExtension.ProvideValue(IServiceProvider serviceProvider) in D:\a\XAMLMarkupExtensions\XAMLMarkupExtensions\src\Base\NestedMarkupExtension.cs:line 286
   at System.Windows.StyleHelper.GetInstanceValue(UncommonField`1 dataField, DependencyObject container, FrameworkElement feChild, FrameworkContentElement fceChild, Int32 childIndex, DependencyProperty dp, Int32 i, EffectiveValueEntry& entry)
   at System.Windows.StyleHelper.GetChildValueHelper(UncommonField`1 dataField, ItemStructList`1& valueLookupList, DependencyProperty dp, DependencyObject container, FrameworkObject child, Int32 childIndex, Boolean styleLookup, EffectiveValueEntry& entry, ValueLookupType& sourceType, FrameworkElementFactory templateRoot)
   at System.Windows.StyleHelper.GetChildValue(UncommonField`1 dataField, DependencyObject container, Int32 childIndex, FrameworkObject child, DependencyProperty dp, FrugalStructList`1& childRecordFromChildIndex, EffectiveValueEntry& entry, ValueLookupType& sourceType, FrameworkElementFactory templateRoot)
   at System.Windows.StyleHelper.GetValueFromTemplatedParent(DependencyObject container, Int32 childIndex, FrameworkObject child, DependencyProperty dp, FrugalStructList`1& childRecordFromChildIndex, FrameworkElementFactory templateRoot, EffectiveValueEntry& entry)
   at System.Windows.StyleHelper.ApplyTemplatedParentValue(DependencyObject container, FrameworkObject child, Int32 childIndex, FrugalStructList`1& childRecordFromChildIndex, DependencyProperty dp, FrameworkElementFactory templateRoot)
   at System.Windows.StyleHelper.InvalidatePropertiesOnTemplateNode(DependencyObject container, FrameworkObject child, Int32 childIndex, FrugalStructList`1& childRecordFromChildIndex, Boolean isDetach, FrameworkElementFactory templateRoot)
   at System.Windows.FrameworkTemplate.InvalidatePropertiesOnTemplate(DependencyObject container, Object currentObject)
   at System.Windows.FrameworkTemplate.HandleBeforeProperties(Object createdObject, DependencyObject& rootObject, DependencyObject container, FrameworkElement feContainer, INameScope nameScope)
   at System.Windows.FrameworkTemplate.<>c__DisplayClass45_0.<LoadOptimizedTemplateContent>b__2(Object sender, XamlObjectEventArgs args)
   at System.Xaml.XamlObjectWriter.OnBeforeProperties(Object value)
   at System.Xaml.XamlObjectWriter.Logic_CreateAndAssignToParentStart(ObjectWriterContext ctx)
   at System.Xaml.XamlObjectWriter.WriteEndObject()
   at System.Windows.FrameworkTemplate.LoadTemplateXaml(XamlReader templateReader, XamlObjectWriter currentWriter)
   --- End of inner exception stack trace ---
   at System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
   at System.Windows.FrameworkTemplate.LoadTemplateXaml(XamlReader templateReader, XamlObjectWriter currentWriter)
   at System.Windows.FrameworkTemplate.LoadTemplateXaml(XamlObjectWriter objectWriter)
   at System.Windows.FrameworkTemplate.LoadOptimizedTemplateContent(DependencyObject container, IComponentConnector componentConnector, IStyleConnector styleConnector, List`1 affectedChildren, UncommonField`1 templatedNonFeChildrenField)
   at System.Windows.FrameworkTemplate.LoadContent(DependencyObject container, List`1 affectedChildren)
   at System.Windows.StyleHelper.ApplyTemplateContent(UncommonField`1 dataField, DependencyObject container, FrameworkElementFactory templateRoot, Int32 lastChildIndex, HybridDictionary childIndexFromChildID, FrameworkTemplate frameworkTemplate)
   at System.Windows.FrameworkTemplate.ApplyTemplateContent(UncommonField`1 templateDataField, FrameworkElement container)
   at System.Windows.FrameworkElement.ApplyTemplate()
   at System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   at System.Windows.UIElement.Measure(Size availableSize)
   at System.Windows.ContextLayoutManager.UpdateLayout()
   at System.Windows.ContextLayoutManager.UpdateLayoutCallback(Object arg)
   at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by konne** [comment]
@Karnah can you please have a look.
It seams to have an Dictionary Check error here: AddTargetObjectProperty

**Comment by Karnah** [comment]
@ondrasvoboda, sorry, I can't reproduce this exception. Could you create a sample project?
@konne, I checked this method and it's called only in one place. The key for this dictionary is created or found just before the method call. I don't have any good idea about this problem. Probably it can be connected with race conditions but why now?

**Comment by ondrasvoboda** [comment]
Unfortunately I don't have any sample, I don't even know how to provoke it in my app. It just shows up "sometimes" - e.g. I open the same window 5 times with no error and next time there is this exception.
I reverted back to 2.0.0 and since then I haven't seen it.

**Comment by Psykobal** [comment]
I ran into this exception too. I can't make a sample project but I found after some try that, in some circumstances, the WeakReference added in:
` wr = targetObjects.AddTargetObject(targetObject);` (NestedMarkupExtension.cs, line 276)
is remove right after in:
`ObjectDependencyManager.AddObjectDependency(wr, this);` (NestedMarkupExtension.cs, line 279)
(full stack: 
` at XAMLMarkupExtensions.Base.TargetObjectsList.Clear()
   at XAMLMarkupExtensions.Base.NestedMarkupExtension.XAMLMarkupExtensions.Base.IObjectDependency.OnAllDependenciesRemoved()
   at XAMLMarkupExtensions.Base.ObjectDependencyManager.CleanUp(Object objToRemove)
   at XAMLMarkupExtensions.Base.ObjectDependencyManager.CleanUp()
   at XAMLMarkupExtensions.Base.ObjectDependencyManager.AddObjectDependency(WeakReference weakRefDp, Object objToHold)
   at XAMLMarkupExtensions.Base.NestedMarkupExtension.ProvideValue(IServiceProvider serviceProvider)`

I think the problem comes from the fact that `ObjectDependencyManager.AddObjectDependency(wr, this);` start with `Cleanup` and this cleanup could call (in some case) `OnAllDependenciesRemoved`, this one will clear `targetObjects` and the new WeakReference with it (before it's added to `ObjectDependencyManager.internalList`).

Maybe the `Cleanup` call should be done at the end of `public static bool AddObjectDependency(WeakReference weakRefDp, object objToHold)`
